# Originally contributed by @rbuffat to Toblerity/Fiona
# https://github.com/Toblerity/Shapely/blob/master/.travis.yml
dist: xenial
group: travis_latest
language: python
sudo: false

notifications:
    email: false

cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild

matrix:
  fast_finish: true
  include:
    - python: 2.7
      stage: py27-gdal2.3
      env:
        - TOXENV=py27-gdal2.3
        - GDALVERSION="2.3.2"

    - python: 3.7
      stage: py37-gdal2.3
      env:
        - TOXENV=py37-gdal2.3
        - GDALVERSION="2.3.2"

addons:
  apt:
    packages:
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libpng12-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=/usr/share/proj
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - gdal-config --version
  - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
install:
  - pip install -U pip tox
before_script:
  - pip install -U pylama isort
  - pylama --options setup.cfg
  - isort --recursive --check-only
script:
  - tox
after_success:
  - coveralls
