# Originally contributed by @rbuffat to Toblerity/Fiona
# https://github.com/Toblerity/Shapely/blob/master/.travis.yml
language: python
sudo: false
notifications:
    email: false
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
  matrix:
    - GDALVERSION="2.0.1"
    - GDALVERSION="2.1.3"
    - GDALVERSION="2.2.0"
    - GDALVERSION="2.3.1"
addons:
  apt:
    packages:
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libpng12-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - "pip install -U pip wheel coveralls setuptools"
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=/usr/share/proj
  - "whereis gdal"
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - gdal-config --version
install:
  - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - "pip install GDAL==$GDALVERSION"
  - "pip install -U -e .[test]"
before_script:
  - pip install -U pylama isort
  - pylama --options setup.cfg
  - isort --recursive --check-only
script:
  - pytest
after_success:
  - coveralls
